name: Generate Podcast Feed
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Seting up the environment and dependencies
      - name: Checkout Repo
        uses: actions/checkout@v6.0.2
      - name: Run Podcast Feed Generator
        uses: jassoncodes/podcast-generator@main

# Commented to use the jassoncodes/podcast-generator actions
#      - name: Setup Python
#        uses: actions/setup-python@v6.1.0
#        with: 
#          python-version: '3.10'
#      - name: Install Dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pyyaml
#      - name: Run feed generator
#        run: python feed.py
#      - name: Push Repo
#        run: |
#          git config user.name github-actions
#          git config user.email github-actions@github.com
#          git add .
#          git commit -m "Modified Feed"
#          git push
          
          
